#pragma once
#include <windows.h>
#include <windowsx.h>
#include <d3d11.h>
#include <d3dx11.h>
#include <d3dx10.h>
#include "Timer.h"
#include "utils.h"
#include "gameOptions.h"
#include "globalDeclarations.h"
#include <vector>
#include "Components.h"
#include <stdlib.h>
#include <chrono>
#include <algorithm>